dist: bionic
language: go

services:
  - docker

go:
  - 1.12.x
  - 1.13.x
  # - master

matrix:
  fast_finish: true
  allow_failures:
    - go: master

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

env:
  global:
    - MASTER_IMAGE=percona:5.7
    - SLAVE_IMAGE=percona:5.7
    - CODECOV_ENV=PROXYSQL_IMAGE,PROXYSQL_CNF,PROXYSQL_CNF_DEST,MASTER_IMAGE,SLAVE_IMAGE

  matrix:
    - PROXYSQL_IMAGE=percona/proxysql:latest  PROXYSQL_CNF=proxysql1.cnf PROXYSQL_CNF_DEST=/etc/proxysql.cnf
    - PROXYSQL_IMAGE=percona/proxysql2:latest PROXYSQL_CNF=proxysql2.cnf PROXYSQL_CNF_DEST=/etc/proxysql/proxysql.cnf

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose up -d

script:
  - make format build testall

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: RJipNzbg9ypZfIGFyfSQSGh4XFh1psVs8hKr7HAK3pwFl1lSaoErjxHgNA7zrQ+G3z1CyCx6McPAjJG8pcijCJVV8TAikVNJmW3kp5BA7X4agi24/tUOzkiATLf+O6SyTn22NUe3INTxJx7mYBvA3YlOaMobBFT1eBFFl4niekIwilrBWQOdHRZ8GjvTUrd/vLse7mP5OwMDEr8hnKnjX4FNKhORk8iopU/l3V+Po6veBiKbNVK5cn6XQ3Xnw/d3gMX+YOw2B5EMAchloLg85G+HawpjjYs4PDBcVQVYX8fwVhkGcyl1cStQ97aE8t5L3qPXPVgeNQnbViPsXzQ1lbcnd1l7ST+HPBR6Dkr0mTRophbMWgizsldnUiTeSYzjN9NIT3INCleofycCy2+Aasqdfi5BWMy5L07bLs98VWTJq38fdwCACgS1Btyl/wAqkp12PHDw51bg6B4un0tEEG8ySB3jI0Flo+XCTIUK8Oc+rQCRiQiN5AqT6eDtrEiIGmN9Tj1xGp4Znf6GhZssR/nAO5VH5G9kwVXUUUJy6UJ0Qe63KwSUROjauNTFBpwvKlXvxcup03ZoxJ3Wmg6fcTe9/HvhA7ocx3EkiPsuKHcur8/6W+aiKLCeiUUtq1WcUv2p2w21o3jyQ0KjG3gBJqq3KWrjW6ArATHCnK6DCQs=
